import 'package:flutter/material.dart';

enum PrizePayoutStatus { processing, credited, failed }

class PrizePayout {
  const PrizePayout({
    required this.id,
    required this.txnId,
    required this.tournament,
    required this.sportIcon,
    required this.title,
    required this.prizeIcon,
    required this.netAmount,
    required this.grossAmount,
    required this.feeAmount,
    required this.status,
    required this.listDate,
    required this.detailDate,
    required this.descriptionTitle,
    required this.awardedTo,
    required this.teamName,
    required this.awardedBy,
    required this.awardedByNote,
    this.paymentMethod,
  });

  final String id;
  final String txnId;
  final String tournament;
  final IconData sportIcon;
  final String title;
  final IconData prizeIcon;
  final int netAmount;
  final int grossAmount;
  final int feeAmount;
  final PrizePayoutStatus status;
  final String listDate;
  final String detailDate;
  final String descriptionTitle;
  final String awardedTo;
  final String teamName;
  final String awardedBy;
  final String awardedByNote;
  final String? paymentMethod;
}

const dummyPrizesTotalEarned = '₹ 1,20,400';
const dummyPrizesTournamentWins = 3;
const dummyPrizesIndividualAwards = 8;
const dummyPrizesPending = '₹26,000';

const dummyPrizePayouts = [
  PrizePayout(
    id: 'pz-1',
    txnId: 'TXN-88210',
    tournament: 'ABC Premier League 2026',
    sportIcon: Icons.sports_cricket_rounded,
    title: 'Winning Team',
    prizeIcon: Icons.emoji_events_rounded,
    netAmount: 4500,
    grossAmount: 5000,
    feeAmount: 500,
    status: PrizePayoutStatus.processing,
    listDate: 'Aug 2, 2026',
    detailDate: '22 September 2026',
    descriptionTitle: 'Kondapur Super Over Cup',
    awardedTo: 'Zoto',
    teamName: 'SPOTO Warriors',
    awardedBy: 'XYZ Cricket Academy',
    awardedByNote: '(SPOTO Partner)',
  ),
  PrizePayout(
    id: 'pz-2',
    txnId: 'TXN-88211',
    tournament: 'ABC Premier League 2026',
    sportIcon: Icons.sports_cricket_rounded,
    title: 'Player of the Tournament',
    prizeIcon: Icons.star_rounded,
    netAmount: 5000,
    grossAmount: 5556,
    feeAmount: 556,
    status: PrizePayoutStatus.processing,
    listDate: 'Aug 2, 2026',
    detailDate: '22 September 2026',
    descriptionTitle: 'Kondapur Super Over Cup',
    awardedTo: 'Zoto',
    teamName: 'SPOTO Warriors',
    awardedBy: 'XYZ Cricket Academy',
    awardedByNote: '(SPOTO Partner)',
  ),
  PrizePayout(
    id: 'pz-3',
    txnId: 'TXN-88213',
    tournament: 'Hyderabad Corporate Cup',
    sportIcon: Icons.sports_cricket_rounded,
    title: 'Best Player of the Final',
    prizeIcon: Icons.military_tech_rounded,
    netAmount: 2700,
    grossAmount: 3000,
    feeAmount: 300,
    status: PrizePayoutStatus.credited,
    listDate: 'Aug 2, 2026',
    detailDate: '22 September 2026',
    descriptionTitle: 'Kondapur Super Over Cup',
    awardedTo: 'Zoto',
    teamName: 'SPOTO Warriors',
    awardedBy: 'XYZ Cricket Academy',
    awardedByNote: '(SPOTO Partner)',
    paymentMethod: 'UPI - PhonePe',
  ),
  PrizePayout(
    id: 'pz-4',
    txnId: 'TXN-88214',
    tournament: 'Old City Football Cup',
    sportIcon: Icons.sports_soccer_rounded,
    title: 'Golden Boot',
    prizeIcon: Icons.sports_rounded,
    netAmount: 1530,
    grossAmount: 1700,
    feeAmount: 170,
    status: PrizePayoutStatus.failed,
    listDate: 'Aug 2, 2026',
    detailDate: '22 September 2026',
    descriptionTitle: 'Kondapur Super Over Cup',
    awardedTo: 'Zoto',
    teamName: 'SPOTO Warriors',
    awardedBy: 'XYZ Cricket Academy',
    awardedByNote: '(SPOTO Partner)',
  ),
  PrizePayout(
    id: 'pz-5',
    txnId: 'TXN-88215',
    tournament: 'Kukatpally Night Cup',
    sportIcon: Icons.sports_cricket_rounded,
    title: 'Best Batsman',
    prizeIcon: Icons.sports_cricket_rounded,
    netAmount: 2700,
    grossAmount: 3000,
    feeAmount: 300,
    status: PrizePayoutStatus.credited,
    listDate: 'Aug 2, 2026',
    detailDate: '22 September 2026',
    descriptionTitle: 'Kondapur Super Over Cup',
    awardedTo: 'Zoto',
    teamName: 'SPOTO Warriors',
    awardedBy: 'XYZ Cricket Academy',
    awardedByNote: '(SPOTO Partner)',
    paymentMethod: 'UPI - PhonePe',
  ),
  PrizePayout(
    id: 'pz-6',
    txnId: 'TXN-88216',
    tournament: 'Secunderabad Smash Open',
    sportIcon: Icons.sports_tennis_rounded,
    title: 'Winner',
    prizeIcon: Icons.emoji_events_rounded,
    netAmount: 8100,
    grossAmount: 9000,
    feeAmount: 900,
    status: PrizePayoutStatus.credited,
    listDate: 'Jul 18, 2026',
    detailDate: '20 July 2026',
    descriptionTitle: 'Secunderabad Smash Open',
    awardedTo: 'Zoto',
    teamName: 'SPOTO Warriors',
    awardedBy: 'Ace Arena Partners',
    awardedByNote: '(SPOTO Partner)',
    paymentMethod: 'UPI - GPay',
  ),
  PrizePayout(
    id: 'pz-7',
    txnId: 'TXN-88217',
    tournament: 'Ameerpet Super Over',
    sportIcon: Icons.sports_cricket_rounded,
    title: 'Best Bowler',
    prizeIcon: Icons.sports_baseball_rounded,
    netAmount: 1800,
    grossAmount: 2000,
    feeAmount: 200,
    status: PrizePayoutStatus.credited,
    listDate: 'Jul 12, 2026',
    detailDate: '14 July 2026',
    descriptionTitle: 'Ameerpet Super Over',
    awardedTo: 'Zoto',
    teamName: 'SPOTO Warriors',
    awardedBy: 'Deccan Sports Traders',
    awardedByNote: '(SPOTO Partner)',
    paymentMethod: 'Wallet',
  ),
  PrizePayout(
    id: 'pz-8',
    txnId: 'TXN-88218',
    tournament: 'Gachibowli Night Cup',
    sportIcon: Icons.sports_cricket_rounded,
    title: 'Man of the Match',
    prizeIcon: Icons.military_tech_rounded,
    netAmount: 2250,
    grossAmount: 2500,
    feeAmount: 250,
    status: PrizePayoutStatus.credited,
    listDate: 'Jul 4, 2026',
    detailDate: '6 July 2026',
    descriptionTitle: 'Gachibowli Night Cup',
    awardedTo: 'Zoto',
    teamName: 'SPOTO Warriors',
    awardedBy: 'Hyderabad Sport Co.',
    awardedByNote: '(SPOTO Partner)',
    paymentMethod: 'UPI - PhonePe',
  ),
  PrizePayout(
    id: 'pz-9',
    txnId: 'TXN-88219',
    tournament: 'Charminar Football Cup',
    sportIcon: Icons.sports_soccer_rounded,
    title: 'Golden Glove',
    prizeIcon: Icons.sports_handball_rounded,
    netAmount: 1350,
    grossAmount: 1500,
    feeAmount: 150,
    status: PrizePayoutStatus.failed,
    listDate: 'Jun 28, 2026',
    detailDate: '30 June 2026',
    descriptionTitle: 'Charminar Football Cup',
    awardedTo: 'Zoto',
    teamName: 'SPOTO Warriors',
    awardedBy: 'Hyderabad Sport Co.',
    awardedByNote: '(SPOTO Partner)',
  ),
  PrizePayout(
    id: 'pz-10',
    txnId: 'TXN-88220',
    tournament: 'Madhapur Kabaddi Clash',
    sportIcon: Icons.sports_rounded,
    title: 'Best Raider',
    prizeIcon: Icons.flash_on_rounded,
    netAmount: 900,
    grossAmount: 1000,
    feeAmount: 100,
    status: PrizePayoutStatus.failed,
    listDate: 'Jun 20, 2026',
    detailDate: '22 June 2026',
    descriptionTitle: 'Madhapur Kabaddi Clash',
    awardedTo: 'Zoto',
    teamName: 'SPOTO Warriors',
    awardedBy: 'Ameerpet Sports Hub',
    awardedByNote: '(SPOTO Partner)',
  ),
  PrizePayout(
    id: 'pz-11',
    txnId: 'TXN-88221',
    tournament: 'Banjara Hills Open',
    sportIcon: Icons.sports_tennis_rounded,
    title: 'Runner-Up',
    prizeIcon: Icons.workspace_premium_rounded,
    netAmount: 2700,
    grossAmount: 3000,
    feeAmount: 300,
    status: PrizePayoutStatus.failed,
    listDate: 'Jun 11, 2026',
    detailDate: '12 June 2026',
    descriptionTitle: 'Banjara Hills Open',
    awardedTo: 'Zoto',
    teamName: 'SPOTO Warriors',
    awardedBy: 'Ace Arena Partners',
    awardedByNote: '(SPOTO Partner)',
  ),
];
