// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyD74ljNwPpGqEgLHuot2jpnpi6cLo2U26w",
    projectId: "zoto-c5c7d",
    storageBucket: "zoto-c5c7d.firebasestorage.app",
    appId: "1:1053360074312:android:946de32a2295cb09d6327d",
    messagingSenderId: '1053360074312',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyCasHweLBkAvZ-YD-rmKrlN0QvZg1V5C9U",
    appId: "1:1053360074312:ios:fca54cdb26b9e1e6d6327d",
    messagingSenderId: "1053360074312",
    projectId: "zoto-c5c7d",
    storageBucket: "zoto-c5c7d.firebasestorage.app",
    iosBundleId: "com.zoto.user",
  );
}
